### ISSUE TITLE
Requires magento/framework >=101.0 -> no matching package found.

### ISSUE THREAD

**Issue by mrk-dzie** [swissup/module-marketplace#11]
When i try to install swissup/module-marketplace 1.7.4 with Mangeto 2.3.5-p1 i get error:
swissup/module-marketplace 1.7.4 requires magento/framework >=101.0 -> no matching package found.

I have install "magento/framework": "102.0.5"

**Comment by vovayatsyuk** [comment]
Try to run ‘composer show magento/framework’ in terminal. Please attach the output here.

**Comment by mrk-dzie** [comment]
@vovayatsyuk Here it is:
`name     : magento/framework
descrip. : N/A
keywords : 
versions : * 102.0.5
type     : magento2-library
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
license  : Academic Free License v3.0 (AFL-3.0) (OSI approved) https://spdx.org/licenses/AFL-3.0.html#licenseText
homepage : 
source   : []  
dist     : [zip] https://repo.magento.com/archives/magento/framework/magento-framework-102.0.5.0.zip 
path     : /var/www/box/vendor/magento/framework
names    : magento/framework

autoload
psr-4
Magento\Framework\ => .
files

requires
colinmollenhour/php-redis-session-abstract ~1.4.0
composer/composer ^1.9
ext-bcmath *
ext-curl *
ext-dom *
ext-gd *
ext-hash *
ext-iconv *
ext-intl *
ext-openssl *
ext-simplexml *
ext-xsl *
guzzlehttp/guzzle ^6.3.3
laminas/laminas-code ~3.3.0
laminas/laminas-crypt ^2.6.0
laminas/laminas-http ^2.6.0
laminas/laminas-mail ^2.9.0
laminas/laminas-mime ^2.5.0
laminas/laminas-mvc ~2.7.0
laminas/laminas-stdlib ^3.2.1
laminas/laminas-uri ^2.5.1
laminas/laminas-validator ^2.6.0
lib-libxml *
magento/zendframework1 ~1.14.2
monolog/monolog ^1.17
php ~7.1.3||~7.2.0||~7.3.0
symfony/console ~4.1.0||~4.2.0||~4.3.0||~4.4.0
symfony/process ~4.1.0||~4.2.0||~4.3.0||~4.4.0
tedivm/jshrink ~1.3.0
wikimedia/less.php ~1.8.0

suggests
ext-imagick Use Image Magick >=3.0.0 as an optional alternative image processing library`

**Comment by vovayatsyuk** [comment]
That is weird. 🤔

Do you run ‘composer require swissup/module-marketplace’ in the same folder?
