### ISSUE TITLE
At latest version of package seem not compatible with magento code 2.4-develop

### ISSUE THREAD

**Issue by mrtuvn** [swissup/module-marketplace#15]
declaration of Swissup\Marketplace\Model\Logger\Handler::setFormatter(Monolog\Formatter\FormatterInterface $formatter) must be compatible with Monolog\Handler\AbstractProcessingHandler::setFormatter(Monolog\Formatter\FormatterInterface $formatter): Monolog\Handler\HandlerInterface in /var/www/html/vendor/swissup/module-marketplace/Model/Logger/Handler.php on line 13
```json
"swissup/breeze": "^1.6.4",
"swissup/module-marketplace": "1.9.1"
```

Not too critical but i think something changed maybe from magento end or third-party packages

**Comment by vovayatsyuk** [comment]
Thanks for reporting!
