### ISSUE TITLE
How to use in CI

### ISSUE THREAD

**Issue by amenk** [swissup/module-marketplace#8]
How can we store the Swissup credentials in our git repository to install the modules in CI?

is there a way to automate the authentication step?

**Comment by vovayatsyuk** [comment]
Hi! Do you store Magento Marketplace or other credentials already? It should work in the same way.

**Comment by amenk** [comment]
The Swissuo credentials did not seem to end up in auth.json
But it is supposed to, right?

**Comment by vovayatsyuk** [comment]
Current module version saves and reads credentials to magento_root/var/composer_home/auth.json.

P.s. Additionally, to get all other possible credentials we merge values from ~/.composer/auth.json and magento_root/auth.json into magento_root/var/composer_home/auth.json

**Comment by amenk** [comment]
Okay. so it should work to copy the data from composer_home/auth.json to the repo root auth.json?

Do we have to expect problems with the numerous different dev and test domains we have or can they all use the same auth data for the same project?

**Comment by vovayatsyuk** [comment]
How did you manage to install all of the sites with different `base_url` settings? Did you use some script for that? Can you insert the correct domain name into auth.json in a similar way?

p.s. While it will work with an invalid domain (previously activated) in auth data, I recommend using a valid one.

**Comment by amenk** [comment]
Yes we use some scripting for this. Thanks, seems to work
